/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Mainstream Token",
  "tagline": "With An Experimental Token-Based Rights Management Protocol",
  "favicon": "img/mtlogo.png",
  "url": "https://mainstreamorganization.github.io",
  "baseUrl": "/mainstreamtoken.com/",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "organizationName": "mainstreamorganization",
  "projectName": "mainstreamtoken",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/mainstreamorganization/mainstreamtoken/tree/main/"
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "routeBasePath": "news",
          "path": "./news",
          "editUrl": "https://github.com/mainstreamorganization/mainstreamtoken/tree/main/",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "Mainstream Token",
      "logo": {
        "alt": "Mainstream Token Logo",
        "src": "img/mnstrmlogo.png"
      },
      "items": [
        {
          "to": "/docs/whitepaper/table_of_contents",
          "label": "Whitepaper",
          "position": "left"
        },
        {
          "to": "/docs/license/overview",
          "type": "dropdown",
          "label": "License",
          "position": "left",
          "items": [
            {
              "label": "License v0.1",
              "to": "/docs/versions/v0/license"
            },
            {
              "label": "License Parameters v0.1",
              "to": "/docs/versions/v0/parameters"
            },
            {
              "label": "Tutorial",
              "to": "/docs/tutorial/encoder-decoder"
            }
          ]
        },
        {
          "to": "/news",
          "label": "News",
          "position": "left"
        },
        {
          "href": "https://github.com/mainstreamorganization/mainstreamtoken",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "dropdown",
          "label": "Apps",
          "position": "left",
          "items": [
            {
              "label": "MTL Generator",
              "to": "/app/encoder"
            },
            {
              "label": "MTL Decoder",
              "to": "/app/decoder"
            },
            {
              "label": "Make MTL Payment",
              "to": "/app/payment"
            }
          ]
        },
        {
          "to": "/contact",
          "label": "Contact",
          "position": "left"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Mainstream Token",
          "items": [
            {
              "label": "Experimental digital rights\nmanagement through\nblockchain technology.",
              "to": "#"
            }
          ]
        },
        {
          "title": "Cloud Tags",
          "items": [
            {
              "label": "#MainstreamToken",
              "to": "/news/tags/mainstreamtoken"
            },
            {
              "label": "#MTLProtocol",
              "to": "/news/tags/mtlprotocol"
            },
            {
              "label": "#DigitalRights",
              "to": "/news/tags/digitalrights"
            },
            {
              "label": "#Blockchain",
              "to": "/news/tags/blockchain"
            },
            {
              "label": "#AI",
              "to": "/news/tags/ai"
            }
          ]
        },
        {
          "title": "Links",
          "items": [
            {
              "label": "Whitepaper",
              "to": "/docs/whitepaper/table_of_contents"
            },
            {
              "label": "Tokenomics",
              "to": "/docs/tokenomics/distribution"
            },
            {
              "label": "License v0.1",
              "to": "/docs/versions/v0/license"
            },
            {
              "label": "Tutorial",
              "to": "/docs/tutorial/encoder-decoder"
            },
            {
              "label": "How To Buy $MAIN",
              "to": "/docs/tutorial/buy-mt-tokens"
            },
            {
              "label": "News",
              "to": "/news"
            },
            {
              "label": "MTL Generator",
              "to": "/app/encoder"
            },
            {
              "label": "MTL Decoder",
              "to": "/app/decoder"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/mainstreamorganization/mainstreamtoken"
            },
            {
              "label": "Discussions",
              "href": "https://github.com/mainstreamorganization/mainstreamtoken/discussions"
            },
            {
              "label": "Telegram",
              "href": "https://t.me/mainstreamtoken"
            },
            {
              "label": "X",
              "href": "https://x.com/mnstrmtoken"
            }
          ]
        }
      ],
      "copyright": "<span style=\"color: #444;\">© 2025 Mainstream Token. All Rights Reserved.</span>"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
